#!/usr/bin/env python3
"""
Extract key metrics from NCU CSV files generated by gemm_ncu.slurm.

Extracts:
  - dram__throughput.avg.pct_of_peak_sustained_elapsed
  - lts__throughput.avg.pct_of_peak_sustained_elapsed
  - smsp__pipe_tensor_cycles_active.sum / smsp__cycles_elapsed.sum (tensor utilization)

Usage:
  python extract_ncu_metrics.py [csv_file ...]
  python extract_ncu_metrics.py   # discovers gemm_bottleneck_*.csv in cwd
"""

import argparse
import csv
import glob
import math
import os
import sys


def _parse_num(s: str) -> float:
    """Parse numeric string, stripping commas (NCU uses thousands separators)."""
    if s is None or (isinstance(s, str) and s.strip() == ""):
        return float("nan")
    t = str(s).replace(",", "").strip()
    try:
        return float(t)
    except ValueError:
        return float("nan")


def extract_metrics(csv_path: str) -> list[dict]:
    """Read CSV and return list of dicts with extracted metrics per kernel row."""
    required = [
        "dram__throughput.avg.pct_of_peak_sustained_elapsed",
        "lts__throughput.avg.pct_of_peak_sustained_elapsed",
        "smsp__pipe_tensor_cycles_active.sum",
        "smsp__cycles_elapsed.sum",
    ]
    results = []
    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        headers = reader.fieldnames
        if not headers:
            return results
        missing = [c for c in required if c not in headers]
        if missing:
            raise KeyError(f"CSV missing columns: {missing}")

        for row in reader:
            # Skip units row (row with no ID or empty numeric values)
            id_val = row.get("ID", "").strip()
            if id_val == "" and not any(row.get(c, "").strip() for c in required):
                continue

            dram = _parse_num(row["dram__throughput.avg.pct_of_peak_sustained_elapsed"])
            lts = _parse_num(row["lts__throughput.avg.pct_of_peak_sustained_elapsed"])
            tensor_cycles = _parse_num(row["smsp__pipe_tensor_cycles_active.sum"])
            cycles_elapsed = _parse_num(row["smsp__cycles_elapsed.sum"])

            if cycles_elapsed and cycles_elapsed != 0:
                tensor_util = tensor_cycles / cycles_elapsed
            else:
                tensor_util = float("nan")

            # Skip units row (all metrics non-numeric, e.g. "%")
            if _is_nan(dram) and _is_nan(lts) and _is_nan(tensor_util):
                continue

            results.append({
                "kernel_id": id_val,
                "dram_pct": dram,
                "lts_pct": lts,
                "tensor_util": tensor_util,
            })
    return results


def _is_nan(x: float) -> bool:
    return math.isnan(x)


def main():
    ap = argparse.ArgumentParser(
        description="Extract dram%%, lts%%, and tensor_util from NCU gemm_bottleneck CSV(s)."
    )
    ap.add_argument(
        "csv_files",
        nargs="*",
        help="Paths to gemm_bottleneck_*.csv (default: glob gemm_bottleneck_*.csv in cwd)",
    )
    ap.add_argument(
        "--no-header",
        action="store_true",
        help="Do not print header line",
    )
    ap.add_argument(
        "--summary",
        action="store_true",
        help="Print one line per file (mean across kernels) instead of per-kernel",
    )
    args = ap.parse_args()

    if args.csv_files:
        paths = []
        for p in args.csv_files:
            if os.path.isfile(p):
                paths.append(p)
            else:
                print(f"Warning: not a file, skipping: {p}", file=sys.stderr)
    else:
        paths = sorted(glob.glob("gemm_bottleneck_*.csv"))
        if not paths:
            print("No gemm_bottleneck_*.csv found in current directory.", file=sys.stderr)
            sys.exit(1)

    header_printed = False
    for csv_path in paths:
        try:
            rows = extract_metrics(csv_path)
        except Exception as e:
            print(f"Error reading {csv_path}: {e}", file=sys.stderr)
            continue
        if not rows:
            print(f"No data rows in {csv_path}", file=sys.stderr)
            continue

        if args.summary:
            n = len(rows)
            dram_avg = sum(r["dram_pct"] for r in rows if not math.isnan(r["dram_pct"])) / n
            lts_avg = sum(r["lts_pct"] for r in rows if not math.isnan(r["lts_pct"])) / n
            util_avg = sum(r["tensor_util"] for r in rows if not math.isnan(r["tensor_util"])) / n
            if not header_printed and not args.no_header:
                print("file,dram_pct,lts_pct,tensor_util")
                header_printed = True
            print(f"{csv_path},{dram_avg:.6f},{lts_avg:.6f},{util_avg:.6f}")
        else:
            if not header_printed and not args.no_header:
                print("file,kernel_id,dram_pct,lts_pct,tensor_util")
                header_printed = True
            for r in rows:
                print(f"{csv_path},{r['kernel_id']},{r['dram_pct']:.6f},{r['lts_pct']:.6f},{r['tensor_util']:.6f}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
