## generate configs to run: including deepseek, llama, mixtral
python generate_gemm_configs.py

## submit jobs on slurm:
./submit_gemm_ncu.sh
# default uses gemm_specs_unique.csv (generated by generate_gemm_configs.py), can change in submit_gemm_ncu.sh

# after slurm jobs finish, run:
# prefill_decode_gemm_clusters.ipynb 
# which generates prefill_decode_gemm_clusters.pdf, the plot in the paper